### PR TITLE
Groupby w filter update v1

### PR DESCRIPTION
**Pull request by FrancescElies**
@CarstVaartjes
CC @esc
This PR merges last changes from BCOLZ master official repo and esc:pxd_v3 (https://github.com/Blosc/bcolz/pull/98) and a small 'fix import ndarray'

I ran a couple of groupby functions with different parameters, seems to work fine but please keep in mind that it was not extensively tested.

### CODE REVIEW

**Comment by FrancescElies** [comment]
Summary,
as you will see  last three commits are the merge from bcolz:master and esc:pxd_v3 and the small fix I mentioned before, any other commit comes either from bcolz:master or esc:pxd_v3
https://github.com/FrancescElies/bcolz/commit/026a5b0b08d26267334992b0d668a77eebdf54725
https://github.com/FrancescElies/bcolz/commit/8f46d8d88a206d879fbe9bf53cfff5ef4d90972
https://github.com/FrancescElies/bcolz/commit/026a5b0b08d26267334992b0d668a77eebdf5472

**Comment by CarstVaartjes** [comment]
Hi Francesc, maybe we should start looking at making a fully independent package (on the vf github as a public package there) which is decoupled from bcolz and instead uses the pxd branch from @esc ?
I.e.:
- Make a new github repository (I will make that and make you co-owner there), edit: https://github.com/visualfabriq/bquery
- Transfer the extensions from carray_ext.pyx (factorizations, summarizations, the "in filter" workaround, etc.) to a .pyx there (which cimports the carray_ext.pxd from bcolz) and the extensions from ctable (groupby, cache factor, the filter workaround)
- Et voila, should work ;)

**Comment by FrancescElies** [comment]
Hi Carst,
sounds good to me :) let me know if can help.
I'll close this, is it ok?

**Comment by CarstVaartjes** [comment]
Ok! And yes you can help a lot here ;) (but it can wait till next week of course). Basically all this:
"Transfer the extensions from carray_ext.pyx (factorizations, summarizations, the "in filter" workaround, etc.) to a .pyx there (which cimports the carray_ext.pxd from bcolz) and the extensions from ctable (groupby, cache factor, the filter workaround)"

**Comment by FrancescElies** [comment]
OK, nice!, If I have some free time I'll have a look if I can get something done, let's keep in touch via mail :)
Closing this

**Comment by esc** [comment]
It seems to me, that you may want to read some more about using `git rebase`. That is a command you can use to avoid having to do so called upstream-merges. I.e. merging the upstream branch, i.e. master, into the feature branches. 

Regarding the last commit, you want to me to take that into the pxd_v3?

**Comment by CarstVaartjes** [comment]
hi!

About that last commit: i think the pxd_v3 should avoid any of those cimports from definitions? I.e. dtype, malloc, npy_int32, npy_uint64, npy_int64, npy_float64 can all be directly cimported from numpy in carray_ext? That way you also ensure compatibility with any other package using cython I think...

**Comment by esc** [comment]
Yes the goal is to completely remove any additional numpy stuff in definitions.pxd and everywhere else in the code.

**Comment by FrancescElies** [comment]
Hi,

thanks for the tip about `git rebase`, I had little expirience eith that squashing commits, but not much more, to be sure I understand it correctly, I should have used it to have to rewrite the history and reduce it to three commits one with the fix and the other two containing changes from master and pxd_v3, is that correct?

If you could take the last commit to pxd_v3 would be great (thanks once again:)!

**Comment by esc** [comment]
I think the last commit doesn't alppy, since it is about `ctable_ext.pyx`? Sorry for the confusion.

**Pull request closed without merging**
